// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itosdbawtlfcqtcllcrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0b3NkYmF3dGxmY3F0Y2xsY3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTMxNjAsImV4cCI6MjA2MTE2OTE2MH0.NHth1YVqJN5RkWn4wUfks5WqJ4xVz4bcQ5futJWKf38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);